# Site settings
title: "Peter Hoggarth"
description: "Developer"
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "peterhoggarth.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: "Peter Hoggarth"
#user_description: description
user_title: "Software Developer"
email: "me@peterhoggarth.com"
github_username:  "peterhogg"

# Google-analytics
google-analytics:
  id: "UA-92766571-1"

exclude: ['package.json', 'src' , 'node_modules']
